services:
  # Backend API
  - type: web
    name: influenciadoras-api
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: influenciadoras-db
          property: connectionString

  # Frontend Next.js
  - type: web
    name: influenciadoras-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://influenciadoras-api.onrender.com

databases:
  - name: influenciadoras-db
    databaseName: influenciadoras
    user: influenciadoras 